<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1' => 'Steg 1',
	'LBL_IMPORT_STEP_1_DESCRIPTION' => 'Välj fil',
	'LBL_IMPORT_SUPPORTED_FILE_TYPES' => '	Godkända filtyper: .CSV, .VCF',
	'LBL_IMPORT_STEP_2' => 'Steg 2',
	'LBL_IMPORT_STEP_2_DESCRIPTION' => 'Ange format',
	'LBL_FILE_TYPE' => 'Filtyp',
	'LBL_CHARACTER_ENCODING' => 'Teckenformat',
	'LBL_DELIMITER' => 'Avgränsningstecken',
	'LBL_HAS_HEADER' => 'Har rubrik',
	'LBL_IMPORT_STEP_3' => 'Steg 3',
	'LBL_IMPORT_STEP_3_DESCRIPTION' => 'Dubblettposthantering',
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED' => 'Välj detta alternativ för att aktivera och ställa in sammfogningsdupliceringskriterie',
	'LBL_SPECIFY_MERGE_TYPE' => 'Välj hur dubbletter ska hanteras',
	'LBL_SELECT_MERGE_FIELDS' => 'Välj de matchande fälten för att hitta dubbletter',
	'LBL_AVAILABLE_FIELDS' => 'Tillgängliga fält',
	'LBL_SELECTED_FIELDS' => 'Fält som skall passa till',
	'LBL_NEXT_BUTTON_LABEL' => 'Nästa',
	'LBL_IMPORT_STEP_4' => 'Steg 4',
	'LBL_IMPORT_STEP_4_DESCRIPTION' => 'Mappa kolumnerna till modulfälten',
	'LBL_FILE_COLUMN_HEADER' => 'Rubrik',
	'LBL_ROW_1' => 'Rad 1',
	'LBL_CRM_FIELDS' => 'CRM-fält',
	'LBL_DEFAULT_VALUE' => 'Förvalt belopp',
	'LBL_SAVE_AS_CUSTOM_MAPPING' => 'Spara som anpassad mappning ',
	'LBL_IMPORT_BUTTON_LABEL' => 'Import',
	'LBL_RESULT' => 'Resultat',
	'LBL_TOTAL_RECORDS_IMPORTED' => 'Inlägg Importerades',
	'LBL_NUMBER_OF_RECORDS_CREATED' => 'Inlägg skapades',
	'LBL_NUMBER_OF_RECORDS_UPDATED' => 'Inlägg uppdaterades',
	'LBL_NUMBER_OF_RECORDS_SKIPPED' => 'Inlägg skippade',
	'LBL_NUMBER_OF_RECORDS_MERGED' => 'Inlägg sammanfogade',
	'LBL_TOTAL_RECORDS_FAILED' => 'Inlägg misslyckades',
	'LBL_IMPORT_MORE' => 'Importera fler',
	'LBL_VIEW_LAST_IMPORTED_RECORDS' => 'Senaste importerade Inlägg',
	'LBL_UNDO_LAST_IMPORT' => 'Ångra senaste importering',
	'LBL_FINISH_BUTTON_LABEL' => 'Klar',
	'LBL_UNDO_RESULT' => 'Ångra Import Resultatet',
	'LBL_TOTAL_RECORDS' => 'Totalt Antal Inlägg',
	'LBL_NUMBER_OF_RECORDS_DELETED' => 'Antal inlägg raderade',
	'LBL_OK_BUTTON_LABEL' => 'Ok',
	'LBL_IMPORT_SCHEDULED' => 'Importer schemalagda',
	'LBL_RUNNING' => 'I Drift',
	'LBL_CANCEL_IMPORT' => 'Avbryt import',
	'LBL_ERROR' => 'Fel',
	'LBL_CLEAR_DATA' => 'Rensa data',
	'ERR_UNIMPORTED_RECORDS_EXIST' => 'Inte importera mer data i detta parti. Vänligen starta en ny import.',
	'ERR_IMPORT_INTERRUPTED' => 'Aktuell import har avbrutits. Försök igen senare',
	'ERR_FAILED_TO_LOCK_MODULE' => 'Det gick inte att låsa modul för import. Försök igen senare',
	'LBL_SELECT_SAVED_MAPPING' => 'Välj sparad mappning',
	'LBL_IMPORT_ERROR_LARGE_FILE' => 'Importfel: för stor fil',
	'LBL_FILE_UPLOAD_FAILED' => 'Filuppladdning misslyckades',
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE' => 'Import ändra uppladdningsstorlek',
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE' => 'Import katalog är inte skrivbar',
	'LBL_IMPORT_FILE_COPY_FAILED' => 'Importera filkopia misslyckades',
	'LBL_INVALID_FILE' => 'Ogiltig fil',
	'LBL_NO_ROWS_FOUND' => 'Inga rader funna',
	'LBL_SCHEDULED_IMPORT_DETAILS' => 'Din import har planerats och kommer att starta inom 15 minuter. Du kommer att få ett e-post när importen är klar.  <br> <br>
										Se till att den utgående servern och din e-postadress är konfigurerad till ta emot e-post meddelande',
	'LBL_DETAILS' => 'Detailjer',
	'skipped' => 'Skippade',
	'failed' => 'Misslyckade',
        'Skip'    =>'Skippa',
        'Overwrite' =>'Skriv över',
        'Merge'    =>'Sammanfoga',
);
